version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-node

    steps:
      - checkout

      - run:
          name: Install Python & Dependencies
          command: |
            sudo apt update
            sudo apt install -y python3 python3-pip
            python3 -m pip install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: |
              pip install pytest
              pytest tests/ --junitxml=pytest-report.xml

      - store_artifacts:
          path: pytest-report.xml
          destination: unit-test-report       

      - run:
          name: Run OWASP Dependency Check
          command: |
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip
            ./dependency-check/bin/dependency-check.sh --scan . --format HTML --out reports

      - run:
          name: Run SonarCloud Analysis
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip
            ./sonar-scanner-*/bin/sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

      - store_artifacts:
          path: reports
          destination: dependency-check-report

  docker_build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t codenameab/invoicer:secure .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push codenameab/invoicer:secure

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker_build:
          requires:
            - build
