version: 2.1

jobs:
  scan_and_push_image:
    docker:
      - image: docker:latest
        entrypoint: [""]

    steps:
      # Step 1: Checkout the repository
      - checkout

      # Step 2: Set up remote Docker environment
      - setup_remote_docker:
          version: '20.10.7'
          docker_layer_caching: true
          access_key: $DOCKER_ACCESS_KEY
          secret_key: $DOCKER_SECRET_KEY
          insecure: false  # Disable insecure connections if using official Docker Hub
          force_pull: true  # Always pull the base Docker images

      # Step 3: Build the Docker image
      - run:
          name: Build Docker Image
          command: docker build -t my-app:latest .

      # Step 4: Run Trivy Scan
      - run:
          name: Run Trivy Scan
          command: |
            trivy image --format json --output trivy_report.json my-app:latest
            cat trivy_report.json

      # Step 5: Store Trivy scan results as artifacts
      - store_artifacts:
          path: trivy_report.json
          destination: trivy-reports

      # Step 6: Log in to Docker Hub
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 7: Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push my-app:latest

workflows:
  version: 2
  build_and_scan:
    jobs:
      - scan_and_push_image
